"""recreated db

Revision ID: beca96bb6ecb
Revises: 
Create Date: 2019-03-29 18:10:50.582873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beca96bb6ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_number'), 'batch', ['number'], unique=True)
    op.create_table('profileclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('if_true', sa.String(length=64), nullable=True),
    sa.Column('if_false', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileclass_class_name'), 'profileclass', ['class_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insta_username', sa.String(length=120), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('labelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_insta_username'), 'profile', ['insta_username'], unique=True)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['profileclass.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_timestamp'), 'vote', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_timestamp'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_profile_insta_username'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_profileclass_class_name'), table_name='profileclass')
    op.drop_table('profileclass')
    op.drop_index(op.f('ix_batch_number'), table_name='batch')
    op.drop_table('batch')
    # ### end Alembic commands ###
