"""unique coconstraints

Revision ID: ff56080f2d11
Revises: beca96bb6ecb
Create Date: 2019-04-05 16:23:40.111795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff56080f2d11'
down_revision = 'beca96bb6ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_unique_constraint('session_class_profile_uc', ['session', 'profile_id', 'class_id'])
        batch_op.create_unique_constraint('user_class_profile_uc', ['user_id', 'profile_id', 'class_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('user_class_profile_uc', type_='unique')
        batch_op.drop_constraint('session_class_profile_uc', type_='unique')

    # ### end Alembic commands ###
